<?php

use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\Admin\ExchangeRateController;
use App\Http\Controllers\Admin\KycReviewController;
use App\Http\Controllers\Admin\TradingSettingController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\WalletAdjustmentController;
use App\Http\Controllers\Admin\ReversalController;
use App\Http\Controllers\Admin\WebhookController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\KycController;
use App\Http\Controllers\TradeController;
use App\Http\Controllers\TwoFactorController;
use App\Http\Controllers\EmailVerificationController;
use App\Http\Controllers\UserExportController;
use App\Http\Controllers\BeneficiaryController;
use App\Http\Controllers\MoneyMovementController;
use App\Http\Controllers\Admin\MoneyMovementController as AdminMoneyMovementController;
use App\Http\Controllers\Admin\ComplianceCaseController;
use App\Http\Controllers\Admin\ReconciliationController;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\TransferController;
use App\Http\Controllers\WalletController;
use Illuminate\Support\Facades\Route;

Route::post('/login', [AuthController::class, 'login'])->middleware(['guest', 'throttle:5,1']);
Route::get('/health', function () { try { DB::select('SELECT 1'); return response()->json(['status' => 'healthy', 'timestamp' => now()->toIso8601String(), 'version' => '1.1.0']); } catch (\Throwable) { return response()->json(['status' => 'unavailable', 'timestamp' => now()->toIso8601String()], 503); } })->middleware('throttle:30,1');
Route::post('/2fa/challenge', [TwoFactorController::class, 'challenge'])->middleware(['guest', 'throttle:5,1']);
Route::middleware('auth:sanctum')->group(function () {
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::post('/email/verification/send', [EmailVerificationController::class, 'send'])->middleware('throttle:5,1');
    Route::get('/email/verify/{id}/{hash}', [EmailVerificationController::class, 'verify'])->middleware(['signed', 'throttle:6,1'])->name('verification.verify');
    Route::get('/dashboard', DashboardController::class);
    Route::post('/2fa/enable', [TwoFactorController::class, 'enable'])->middleware(['verified', 'throttle:3,10']);
    Route::post('/2fa/confirm', [TwoFactorController::class, 'confirm'])->middleware(['verified', 'throttle:5,1']);
    Route::delete('/2fa', [TwoFactorController::class, 'disable'])->middleware(['verified', '2fa', 'throttle:3,10']);
    Route::post('/wallets', [WalletController::class, 'store'])->middleware(['verified', '2fa']);
    Route::get('/wallets/{wallet}/transactions', [WalletController::class, 'transactions'])->middleware(['verified', '2fa']);
    Route::post('/transfers', [TransferController::class, 'store'])->middleware(['verified', '2fa', 'throttle:20,1', 'money.idempotent']);
    Route::post('/kyc', [KycController::class, 'store'])->middleware(['verified', '2fa', 'throttle:3,60']);
    Route::post('/trades/quote', [TradeController::class, 'quote'])->middleware(['verified', '2fa', 'throttle:60,1']);
    Route::post('/trades', [TradeController::class, 'store'])->middleware(['verified', '2fa', 'throttle:20,1', 'money.idempotent']);
    Route::get('/beneficiaries', [BeneficiaryController::class, 'index'])->middleware(['verified', '2fa']);
    Route::post('/beneficiaries', [BeneficiaryController::class, 'store'])->middleware(['verified', '2fa', 'throttle:10,1']);
    Route::delete('/beneficiaries/{beneficiary}', [BeneficiaryController::class, 'destroy'])->middleware(['verified', '2fa', 'throttle:10,1']);
    Route::get('/money-movements', [MoneyMovementController::class, 'index'])->middleware(['verified', '2fa']);
    Route::post('/deposits', [MoneyMovementController::class, 'deposit'])->middleware(['verified', '2fa', 'throttle:10,1', 'money.idempotent']);
    Route::post('/withdrawals', [MoneyMovementController::class, 'withdraw'])->middleware(['verified', '2fa', 'throttle:5,1', 'money.idempotent']);
    Route::get('/exports', [UserExportController::class, 'index'])->middleware(['verified', '2fa']);
    Route::post('/exports', [UserExportController::class, 'store'])->middleware(['verified', '2fa', 'throttle:2,60']);
    Route::get('/exports/{userExport}/download', [UserExportController::class, 'download'])->middleware(['verified', '2fa', 'throttle:10,1']);
    Route::prefix('admin')->middleware(['verified', '2fa', 'admin', 'throttle:60,1'])->group(function () {
        Route::get('/dashboard', AdminDashboardController::class);
        Route::post('/users', [UserController::class, 'store'])->middleware('throttle:10,1');
        Route::patch('/users/{user}', [UserController::class, 'update'])->middleware('throttle:30,1');
        Route::post('/currencies', [CurrencyController::class, 'store'])->middleware('throttle:10,1');
        Route::patch('/currencies/{currency}', [CurrencyController::class, 'update'])->middleware('throttle:30,1');
        Route::get('/rates', [ExchangeRateController::class, 'index']);
        Route::post('/rates', [ExchangeRateController::class, 'store'])->middleware('throttle:30,1');
        Route::get('/kyc', [KycReviewController::class, 'index']);
        Route::get('/kyc/{kycSubmission}/document/{side}', [KycReviewController::class, 'document']);
        Route::patch('/kyc/{kycSubmission}', [KycReviewController::class, 'update'])->middleware('throttle:30,1');
        Route::patch('/trading-settings', [TradingSettingController::class, 'update'])->middleware('throttle:10,1');
        Route::post('/wallets/{wallet}/adjust', [WalletAdjustmentController::class, 'store'])->middleware(['throttle:20,1', 'money.idempotent']);
        Route::post('/transactions/{walletTransaction}/reverse', [ReversalController::class, 'store'])->middleware(['throttle:10,1', 'money.idempotent']);
        Route::get('/webhooks', [WebhookController::class, 'index']);
        Route::post('/webhooks', [WebhookController::class, 'store'])->middleware('throttle:10,1');
        Route::delete('/webhooks/{webhook}', [WebhookController::class, 'destroy'])->middleware('throttle:10,1');
        Route::get('/money-movements', [AdminMoneyMovementController::class, 'index']);
        Route::post('/money-movements/{moneyMovement}/approve', [AdminMoneyMovementController::class, 'approve'])->middleware(['throttle:10,1', 'money.idempotent']);
        Route::post('/money-movements/{moneyMovement}/reject', [AdminMoneyMovementController::class, 'reject'])->middleware(['throttle:10,1', 'money.idempotent']);
        Route::post('/money-movements/{moneyMovement}/complete', [AdminMoneyMovementController::class, 'complete'])->middleware(['throttle:10,1', 'money.idempotent']);
        Route::get('/compliance-cases', [ComplianceCaseController::class, 'index']);
        Route::patch('/compliance-cases/{complianceCase}', [ComplianceCaseController::class, 'update'])->middleware('throttle:20,1');
        Route::get('/reconciliations', [ReconciliationController::class, 'index']);
        Route::post('/reconciliations', [ReconciliationController::class, 'store'])->middleware('throttle:3,10');
    });
});
